FROM node:9.11.2-alpine as build-env
MAINTAINER Yann Piquet <yann.piquet@epitech.eu>

RUN mkdir /app
WORKDIR /app

COPY src/package.json .
COPY src/.babelrc .
RUN yarn

COPY src/public ./public
COPY src/src ./src
COPY src/scripts ./scripts
COPY src/config ./config

RUN yarn build

FROM nginx:1.15.0

COPY --from=build-env /app/build/ /usr/share/nginx/html/